### ISSUE TITLE
No way to delete with data types?

### ISSUE THREAD

**Issue by uphoff** [drewkerrigan/riak-elixir-client#10]
I am trying to delete a map from a bucket called "users" of type "maps". It does not appear that this capability is supported. According to the HTTP docs something like `DELETE /types/<type>/buckets/<bucket>/keys/<key>` is needed. Am I missing something or is this not supported?

```
{:ok, riak} = Riak.Connection.start_link('127.0.0.1', 8087) 
m = Riak.find(riak, "maps", "users", "1d1cf86e-e7c8-11e4-b576-542696dfbfa9") |> Riak.CRDT.Map.value
:ok = Riak.delete(riak, "users", "1d1cf86e-e7c8-11e4-b576-542696dfbfa9") # Doesn't delete it
Riak.delete(riak, "maps", "users", "1d1cf86e-e7c8-11e4-b576-542696dfbfa9") # No such function - errors out
```

**Comment by mgresko** [comment]
+1

**Comment by drewkerrigan** [comment]
I'll look into this, didn't realize it's was still open

**Comment by drewkerrigan** [comment]
This should be fixed as of the latest commit; There was no function definition for delete with a bucket type. Technically you should have been able to delete with: Riak.delete(riak, {"maps", "users"}, "1d1cf86e-e7c8-11e4-b576-542696dfbfa9")

But now there is a function for:

Riak.delete(bucket_type, bucket, key)
