### ISSUE TITLE
Fails for Erlang/OTP 18

### ISSUE THREAD

**Issue by blitzstudios** [drewkerrigan/riak-elixir-client#20]
mix deps.get

Compiling src/pooler.erl failed:

src/pooler.erl:209: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.

ERROR: compile failed while processing /Users/xxx/Projects/xxx/app/deps/pooler: rebar_abort
** (Mix) Could not compile dependency :pooler, "/Users/xxx/.mix/rebar" command failed. You can recompile this dependency with "mix deps.compile pooler", update it with "mix deps.update pooler" or clean it with "mix deps.clean pooler"

**Comment by edgurgel** [comment]
We need the last pooler version on hex.pm or just use the last stable git version: https://github.com/seth/pooler/releases/tag/1.5.0

**Comment by weixiyen** [comment]
Also need to update dependencies for both riak-erlang-client (latest head) and riak_pb (2.1.0.7) to be able to compile for OTP 18

**Comment by drewkerrigan** [comment]
Looks to be all good now, yes?

**Comment by weixiyen** [comment]
yep thanks!
