### ISSUE TITLE
Not handling growing concurrency past `init_count` very well

### ISSUE THREAD

**Issue by MaxPower15** [drewkerrigan/riak-elixir-client#25]
Hi there, I'm using Riak in a system that potentially requires high concurrency and have run into an exception that's hard to handle. It looks like this:

```
21:03:45.777 [error] Process #PID<0.192.0> raised an exception
** (FunctionClauseError) no function clause matching in Riak.find/4
    (riak) lib/riak.ex:301: Riak.find(:error_no_members, :error_no_members, "abc", "def")
    (riak) lib/riak.ex:301: Riak.find/3
    (riak) lib/riak.ex:282: Riak.find/2
```

I set up a test repo with instructions to demonstrate: https://github.com/MaxPower15/riak_pooler_issue

I poked around myself with pooler, hoping to maybe get a PR fix, but I don't think I'm familiar enough with the underlying code to really do it correctly. I hope this demo helps though!

**Comment by edgurgel** [comment]
@MaxPower15 I would simply increase your pool https://github.com/drewkerrigan/riak-elixir-client#connection-pooling

Maybe each function should give a better error but it's fair to explode if no connection from the pool is ready to deal with the request.

**Comment by MaxPower15** [comment]
@edgurgel Yes, that's my current solution; I talk about it here: https://github.com/MaxPower15/riak_pooler_issue#explanation. I just think it should be handled better out of the box. :)

**Comment by MaxPower15** [comment]
I should mention, this occurs when requesting a value well _below_ the `max_count`. It just needs to be above the previous minimum value, which is `init_count` in the demo.

**Comment by edgurgel** [comment]
Oh gotcha! I should have read the whole thing! Thanks for the report!

**Comment by edgurgel** [comment]
This issue seems to be the same you noticed: https://github.com/seth/pooler/issues/54

**Comment by MaxPower15** [comment]
Aha, so perhaps a pooler issue. I wonder if it's introduced in a new version. Will try with an older one to see if it can still be reproduced.

**Comment by MaxPower15** [comment]
Well, so much for that idea. I couldn't compile pooler pre-1.5.0. I guess the question is if that's intended behavior or not with pooler.

**Comment by randysecrist** [comment]
Definitely think this is a pooler issue.  I've done some house keeping with pooler recently and fixed some of the compilation issues and warnings including pushing some things up to hex.

Will close this, but will also mention this pooler PR.  Might be worth considering pulling this in but I need to think about it more.

https://github.com/seth/pooler/pull/72
