### ISSUE TITLE
Secondary index querying 

### ISSUE THREAD

**Issue by hytvi** [drewkerrigan/riak-elixir-client#26]
Hi,

I was wondering, is there a possibility to use a secondary index query? 
http://docs.basho.com/riak/latest/dev/using/2i/

**Comment by edgurgel** [comment]
I suppose this is what you are looking for: http://hexdocs.pm/riak/Riak.Index.html

**Comment by hytvi** [comment]
hi @edgurgel, 

Thanks for your reply. Indeed exactly what I am looking for. I couldn't find it in the examples.

Thanks again!
