### ISSUE TITLE
Search argument names are incorrect

### ISSUE THREAD

**Issue by hansonkd** [drewkerrigan/riak-elixir-client#28]
riakc function signature is this:

    create_search_index(Pid::pid(), Index::binary()) -> ok

riak elixir client has

    put(pid, bucket)

This tripped me up when I first came across it, since I thought it was an interface for adding a search index to a bucket's props.

I propose we change the arguments to use `index`.

**Comment by drewkerrigan** [comment]
Yes, pretty sure this is just a copypasta error.
