### ISSUE TITLE
On bucket.save vclock does not get set in return object

### ISSUE THREAD

**Issue by hytvi** [drewkerrigan/riak-elixir-client#30]
Hi guys,

Saving an object using Riak.put will give back an object. This object does not have a vclock, so a sibbling will be created when you update it afterwards.
```
object = Riak.put object # created
object = %{object | data: "Updated"} # update created record
Riak.put object 
```

There is a workaround to prevent the sibbling being created, that is to fetch the record in between and save it then. However, that is an extra query to the database that I would like to prevent.

The object should have an added vclock. I could contribute writing a test for this, but I don't really get where the object is returned. Probably from the erlang library.

**Comment by jesuisbonbon** [comment]
+1

**Comment by drewkerrigan** [comment]
Hello @hytvi, the primary problem here is that when you do a normal PUT against Riak, it does not give you back the vclock. You can verify this with a curl test against the HTTP endpoint:

```
curl -v -XPUT localhost:8098/types/siblings/buckets/test/keys/one -d "testing"
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8098 (#0)
> PUT /types/siblings/buckets/test/keys/one HTTP/1.1
> Host: localhost:8098
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Length: 7
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 7 out of 7 bytes
< HTTP/1.1 204 No Content
< Vary: Accept-Encoding
< Server: MochiWeb/1.1 WebMachine/1.10.8 (that head fake, tho)
< Date: Fri, 22 Jul 2016 17:31:02 GMT
< Content-Type: application/x-www-form-urlencoded
< Content-Length: 0
<
* Connection #0 to host localhost left intact
```

Another thing to keep in mind is that you should always read a value before writing it if you expect it to be an update to an existing object. In an eventually consistent system, if you write to the same key more than once without getting any context about it's existing state, you should expect the inevitability of conflicts, siblings in this case.

 Another work-around is to set the `allow_mult` bucket property to false, but do this at your own risk: http://docs.basho.com/riak/kv/2.1.4/developing/usage/conflict-resolution/
