### ISSUE TITLE
Unable to set a disabled flag on a map

### ISSUE THREAD

**Issue by gausby** [drewkerrigan/riak-elixir-client#32]
I don't know if this is the desired behaviour, but I seems that disabling a flag on a map will cause an error to be raised. The following will show an iex session where a disabled flag is set on a map, which will cause a crash, and one where an enabled flag will be set correctly on a map.
```elixir
iex(1)> Riak.CRDT.Map.new |> Riak.CRDT.Map.put("test", Riak.CRDT.Flag.new |> Riak.CRDT.Flag.disable)
** (throw) :context_required
    (riakc) src/riakc_flag.erl:102: :riakc_flag.disable/1
iex(1)> Riak.CRDT.Map.new |> Riak.CRDT.Map.put("test", Riak.CRDT.Flag.new |> Riak.CRDT.Flag.enable)
{:map, [], [{{"test", :flag}, {:flag, false, :enable, :undefined}}], [],
 :undefined}
iex(2)> 
```
We have discussed this before #19 but I guess having this in an issue would be fitting until we have resolved this issue.

**Comment by drewkerrigan** [comment]
I did some more digging on this, the erlang riak client lib prevents a flag without context from getting disabled: https://github.com/basho/riak-erlang-client/blob/develop/src/riakc_flag.erl#L102

However... I did some hacking and manually created a flag record with a `:disable` op and saved it as new, and Riak didn't seem to mind at all, and correctly returned the value of the flag as false after i did a `Riak.find` on it. I think we can work around this artificial limitation in the riak-erlang-client, but it may be a little sloppy.
