### ISSUE TITLE
Riak.Search.query is reported not defined if taking the pooler route

### ISSUE THREAD

**Issue by gausby** [drewkerrigan/riak-elixir-client#33]
This is a bit weird. I got two projects. One is an app build with `mix phoenix.new`, and the other is a basic `mix new riak_playground` with the riak-elixir-client added to the mix file dependencies and started in the applications—I use the bare bones one to test out stuff with Riak and the Elixir client.

Both apps uses the same pooler configuration. Both apps seem to be able to do most commands, such as `Riak.update`, without specifying the pid—but for some reason `Riak.Search.query` seems to behave differently in my phoenix app. If I type the following In iex:
``` elixir
iex(1)> Riak.Search.query("users", "_yz_rb:profile AND email_register:foo@example.com", rows: 1)
```
It will work just fine, and print the search result. When the same line is copy-pasted into the Phoenix-app it will fail with the following error:
```
[error] #PID<0.1102.0> running MyPhoenixApp.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /auth/identity/callback
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Riak.Search.query/4
        (riak) lib/riak/search.ex:4: Riak.Search.query("users", "_yz_rb:profile AND email_register:foo@example.com", [rows: 1], [])
[... lines omitted ...]
```
I have tried debugging outputting the result of `Kernel.function_exported?(Riak.Search, :query, 4)` which says the function is exported just fine (`true`), and ensured that the Riak application has been started with `Application.ensure_started(:riak)` which reports `:ok`.

The error seems to go away if I set some `pid` as the first argument (a pid such as `self`) to the `Riak.Search.query`, so something might be up with *pooler* or the `defpool`-macro, but I am just guessing.

**Comment by gausby** [comment]
I got it working by:

1) Starting `:pooler` along the other applications in my mix.exs file
2) Creating a helper function for getting an id from the pool
3) Getting a pool id and pass it to `Riak.Search.query`

The helper function I wrote looks like this:
``` elixir
  defp get_pid_from_pool() do
    pid = :pooler.take_group_member(:riak)
    case :pooler.return_group_member(:riak, pid, :ok) do
      :ok ->
        {:ok, pid}

      _ ->
        {:error, :not_member_of_group}
    end
  end
```
It is mostly what the pooler macro in riak-elixir-client does.

**Comment by drewkerrigan** [comment]
Is this still a problem? It sounds like I'd need to set up a phoenix app to properly test and debug this.

**Comment by gausby** [comment]
I just tested it, and the problem seems to have been resolved. Thanks!
