### ISSUE TITLE
Create bucket?

### ISSUE THREAD

**Issue by hopewise** [drewkerrigan/riak-elixir-client#39]
As for the command:

```
o = Riak.Object.create(bucket: "user", key: "my_key", data: "Han Solo")
Riak.put(pid, o)
```

Do I have to create bucket "user" before? or does this command creates the bucket if it does not exist?

**Comment by gausby** [comment]
Hi. Did my answer on the Elixir Forum resolve this?

**Comment by hopewise** [comment]
At least I know now that `put/2` is not for Riak TS, but I still don't know if the above `create/3` for Riak TS or not? and does it create the bucket if it does not exist before?

As I am still learning, I really appreciate a fully working example that targets Riak TS 🙏

**Comment by gausby** [comment]
You need to read the usage documentation. You need to tell Riak TS about your tables, what data goes into them, and the size of the quantum…the official Riak TS documentation does a much better job at explaining this than I can do here.

  * http://docs.basho.com/riak/ts/1.3.0/using/planning/
  * http://docs.basho.com/riak/ts/1.3.0/using/creating-activating/

…and so on.

**Comment by hopewise** [comment]
Thanks, I will read and dig into.. obviously there is a learning curve
there :)

On Sun, May 29, 2016 at 11:37 PM, Martin Gausby <notifications@github.com>
wrote:

> You need to read the usage documentation. You need to tell Riak TS about
> your tables, what data goes into them, and the size of the quantum…the
> official Riak TS documentation does a much better job at explaining this
> than I can do here.
>
>    - http://docs.basho.com/riak/ts/1.3.0/using/planning/
>    - http://docs.basho.com/riak/ts/1.3.0/using/creating-activating/
>
> …and so on.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/drewkerrigan/riak-elixir-client/issues/39#issuecomment-222381363>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABAxJSB5be_wa7XS_mx2dTSGoMc9vVieks5qGfkhgaJpZM4IpQmx>
> .
>



-- 
--
Kind Regards,
---------------------------------------------
Samir Sabri
Software Architect& Developer
www.dcaclab.com
Jordan-Middle East

**Comment by gausby** [comment]
@hopewise sure is :) Could you close the issue if this has been resolved?

**Comment by hopewise** [comment]
Of course:)
