### ISSUE TITLE
Riak TS Support

### ISSUE THREAD

**Issue by kanishkablack** [drewkerrigan/riak-elixir-client#40]

**Comment by gausby** [comment]
There's a timeseries branch here: https://github.com/drewkerrigan/riak-elixir-client/tree/timeseries

You can include it in your project by adding this to your hex dependencies:
```elixir
defp deps do
  [{:riak, github: "drewkerrigan/riak-elixir-client", branch: "timeseries"}]
end
```

**Comment by kanishkablack** [comment]
wow, already in pipeline for support, let me work on it

**Comment by arpunk** [comment]
Official riak Erlang client already supports TS on it's latest release.

**Comment by drewkerrigan** [comment]
Riak TS support has been added (including updated riakc / riak_pb deps in hex). You can test it out in the latest version (1.1.0): https://hex.pm/packages/riak/1.1.0
