### ISSUE TITLE
Riak client disconnects after a couple of minutes

### ISSUE THREAD

**Issue by cdeyoung** [drewkerrigan/riak-elixir-client#47]
Riak-elixir-client hangs after sitting idle for a couple of minutes, and I have to restart Phoenix in order to re-establish a connection to the Riak cluster.  I'm new to Riak, so my configuration may be wrong, but it looks correct, according to the docs.  If my configuration is correct, does anyone have a workaround for this issue?

Here is a little more details and also my configuration settings:

I am running riak-elixir-client in a Phoenix 1.2.0 application on Erlang 19 and Elixir 1.3.2.  My code is running on OS X locally, and several Microsoft Azure instances of Ubuntu 14.04 LTS (I'm seeing the same problem in both places).  When I first start the Phoenix server using

```
    iex -S mix phoenix.server
```

I can pull data from Riak successfully.  For example, 

```
    Riak.find("person", "33")
```

returns the correct data.

However, if I let the server run idle for 2 or 3 minutes, calls to Riak will hang, and eventually end with this error:

[error] GenServer #PID<0.297.0> terminating
*\* (stop) :disconnected
Last message: {:req_timeout, #Reference<0.0.6.2919>}
State: {:state, 'dev-riak-5.example.com', 8087, false, false, :undefined, false, :gen_tcp, :undefined, {[], []}, 1, [], :infinity, :undefined, :undefined, :undefined, :undefined, [], 100}

I then have to either restart Phoenix, or open :observer.start, and kill all the pooler supervisors in order to re-establish a connection to my Riak cluster.

Here are my relevant config settings:

dev.exs and prod.exs pooler configurations:
config :pooler, pools:
  [
    [
      name: :dev_riak_1,
      group: :riak,
      max_count: 20,
      init_count: 5,
      start_mfa: { Riak.Connection, :start_link, ['dev-riak-1.example.com', 8087] }
    ],
    [
      name: :dev_riak_2,
      group: :riak,
      max_count: 20,
      init_count: 5,
      start_mfa: { Riak.Connection, :start_link, ['dev-riak-2.example.com', 8087] }
    ],
    [
      name: :dev_riak_3,
      group: :riak,
      max_count: 20,
      init_count: 5,
      start_mfa: { Riak.Connection, :start_link, ['dev-riak-3.example.com', 8087] }
    ],
    [
      name: :dev_riak_4,
      group: :riak,
      max_count: 20,
      init_count: 5,
      start_mfa: { Riak.Connection, :start_link, ['dev-riak-4.example.com', 8087] }
    ],
    [
      name: :dev_riak_5,
      group: :riak,
      max_count: 20,
      init_count: 5,
      start_mfa: { Riak.Connection, :start_link, ['dev-riak-5.example.com', 8087] }
    ]
  ]

mix.exs:
def application do
    [mod: {Skip, []},
      applications: [
        :cowboy,
        :gettext,
        :httpotion,
        :logger,
        :phoenix,
        :phoenix_html,
        :phoenix_pubsub,
        :phoenix_slime,
        :riak
      ]
    ]
  end
  defp deps do
    [
      {:cowboy, "~> 1.0"},
      {:exrm, "~> 1.0"},
      {:gettext, "~> 0.11"},
      {:httpotion, "~> 3.0.0"},
      {:phoenix, "~> 1.2.0"},
      {:phoenix_html, "~> 2.6"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_slime, "~> 0.7.0"},
      {:relx, github: "erlware/relx", override: true},
      {:riak, "~> 1.0"}
    ]
  end

Thanks for any future answers.

**Comment by cdeyoung** [comment]
I found this issue is a problem with Azure.  Azure kills idle connections after 4 minutes.  I couldn't see a way to solve this problem with the riak-elixir-client library, so worked around the issue by writing a GenServer process that pings the Riak cluster every so often to keep the server from killing the connection.  If the library has this functionality, it would be a great thing to put in the README (maybe it is there and I missed it), if not, it would be a nice thing to add to the pool configuration.

**Comment by drewkerrigan** [comment]
@cdeyoung Thanks for the info, I wasn't aware of that issue in Azure! The functionality to ping / healthcheck the connection every few minutes does not currently exist, but I could see the value in adding it. We can leave this issue open for now to track it.

If you have the time, feel free to submit a PR with something like your GenServer solution, and we can use it as a starting point.

**Comment by cdeyoung** [comment]
This is still an issue on Azure.  While I can keep the client side from timing out, Microsoft still severs the connection on the server side after 4 minutes (or up to 30, if you configure for that).  One thing that might alleviate this issue is the ability to manually set the timeout on client calls, so you don't have to wait for the default (which I think is 60 seconds) to fail.

**Comment by cdeyoung** [comment]
By the way, I didn't do a pull request for my keep-alive function yet, since it only half solved the problem.

**Comment by cdeyoung** [comment]
@drewkerrigan - I've been able to work around the issue for the time being by wrapping Riak calls in Task.async and Task.yield calls.  Here's an example:

`defmodule Riak.Query do
  def find(key, value) do
    find_task = Task.async(fn ->
      Riak.find(key, value)
    end)

    case Task.yield(find_task, 1000) do
      nil -> find(key, value)
      result -> result
    end
  end
end`

**Comment by randysecrist** [comment]
I think a lot of the disconnects going on in the client environment were based on haproxy settings.  Going to close this for now as I have not been able to reproduce.
