### ISSUE TITLE
Compilation issue - undefined function defrecord/3

### ISSUE THREAD

**Issue by tyre** [drewkerrigan/riak-elixir-client#5]
Following the README (added to deps list, `mix deps.get`, `mix`), I get the following compile error:

```
== Compilation error on file lib/riak/object.ex ==
** (CompileError) lib/riak/object.ex:80: undefined function defrecord/3
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (elixir) src/elixir_exp.erl:49: :elixir_exp.expand/2
    (elixir) src/elixir.erl:206: :elixir.quoted_to_erl/3
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3

==> riak-elixir-client
could not compile dependency riak-elixir-client, mix compile failed. You can recompile this dependency with `mix deps.compile riak-elixir-client` or update it with `mix deps.update riak-elixir-client`
```

Erlang/OTP 17 [erts-6.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 0.15.1

**Comment by drewkerrigan** [comment]
I've integrated the work from Riex into this project as well as adding a few new things and fixes. This issue should be fixed now with the latest commits. I'll be tagging version 1.0 of this client in the next few days, but master should be fine too.
