### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cdeyoung** [drewkerrigan/riak-elixir-client#50]
Hi Drew,

This isn't an issue, just a question.  Does your library support nesting Riak.CRDT.Maps inside of each other and parsing the data back out?  Riak.CRDT.Maps.get(map, :map, key) works at the first level, but I can't figure out how to dig deeper than that.  I didn't see any code that looked like it would handle that situation in your repository, but I thought I'd ask.

Thanks.

**Comment by randysecrist** [comment]
nesting is generally discouraged from a CRDT perspective; only in that it makes conflict resolution sorta tough for the application to deal with from a culture perspective.
