### ISSUE TITLE
Pooler can't find riak group when used in umbrella app.

### ISSUE THREAD

**Issue by nav301186** [drewkerrigan/riak-elixir-client#54]
Hi all, I am using riak-elixir-client in an umbrella app and has configured pooler in my config, this works all fine and I able to save and retrieve data from local riak instance as long as I work within this app. 
However,  when I try to use this app from another app within my umbrella project , I get below error on saving :

`** (FunctionClauseError) no function clause matching in Riak.update/5
     stacktrace:
       lib/riak.ex:263: Riak.update({:error_no_group, :riak}, {:map, [], [{{"category_fields", :map}, {:map, [], [{{"sender_id", :register}
, {:register, "", "archer"}}], [], :undefined}}, {{"category_type", :register}, {:register, "", "invitation_request"}}, {{"notification_id"
, :register}, {:register, "", "rin_invitation_request_77353b64-fef4-11e6-a04d-c4b301c08693"}}, {{"user_id", :register}, {:register, "", "ri
n"}}], [], :undefined}, "maps", "notifications", "rin_invitation_request_77353b64-fef4-11e6-a04d-c4b301c08693")
       lib/riak.ex:263: Riak.update/4
       lib/notification_cordinator.ex:12: Paraaz.NotificationCordinator.save/3
       test/controllers/notification_controller_test.exs:20: (test)`

it seems somehow pooler is not able to find riak group.

Code is here : https://github.com/nav301186/rumuk/tree/develop

**Comment by randysecrist** [comment]
I ran into this, and solved it by making sure pooler config was added to the right Mix.env

**Comment by nav301186** [comment]
@randysecrist  yes you are right, so If my app A uses Riak-elixir-client and B uses A, I need to add pooler config in B as well to make it work (I'm using Umbrella app)
