### ISSUE TITLE
Proposal: create hex package

### ISSUE THREAD

**Issue by chvanikoff** [drewkerrigan/riak-elixir-client#9]
Hi,
How about publishing this lib to http://hex.pm? (https://hex.pm/docs/publish)

**Comment by edgurgel** [comment]
To accomplish this we would need to publish these first:

```
{:pooler, github: "seth/pooler", tag: "1.3.3"},
{:riak_pb, github: "basho/riak_pb", override: true, tag: "2.0.0.16", compile: "./rebar get-deps compile deps_dir=../"},
{:riakc, github: "basho/riak-erlang-client", tag: "2.0.1"} ]
```

Git dependencies are not handled by hex, so people would need to add riak-elixir-client + these 3 above.

**Comment by drewkerrigan** [comment]
Yes I'd like to publish to hex asap. I'll probably end up forking the git deps and adding them to hex.

**Comment by lpil** [comment]
:+1:

**Comment by drewkerrigan** [comment]
It was messy, but I managed to get all of the deps and sub-deps into hex, and finally got this into hex:

[https://hex.pm/packages/riak](https://hex.pm/packages/riak)

**Comment by lpil** [comment]
Thanks :)

**Comment by edgurgel** [comment]
@drewkerrigan shall we tag/release on github the same commit hash so we keep them sync'd?

**Comment by drewkerrigan** [comment]
Yes I think that makes sense

**Comment by chvanikoff** [comment]
Great news, thanks! :+1:

**Comment by drewkerrigan** [comment]
@edgurgel v1.0.0 has been tagged by the way

**Comment by edgurgel** [comment]
Awesome! :tada:
